# Generated by Django 5.0.2 on 2024-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
