# Generated by Django 5.0.2 on 2024-05-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
