# Generated by Django 5.0.2 on 2024-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
